# Generated by Django 2.1.1 on 2018-10-05 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyse', '0003_auto_20181005_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 5, 21, 59, 18, 10794)),
        ),
    ]
