# Generated by Django 2.1.1 on 2018-10-05 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyse', '0004_auto_20181005_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 6, 1, 24, 46, 124921)),
        ),
    ]
