# Generated by Django 2.1.1 on 2018-10-05 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyse', '0006_auto_20181006_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 6, 3, 31, 42, 25526)),
        ),
    ]
