# Generated by Django 2.0 on 2018-10-06 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyse', '0008_auto_20181006_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 6, 8, 29, 49, 987879)),
        ),
    ]
